Q.1 Write a program to distinguish between Array Indexing and Fancy Indexing.

In [1]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

simple_indexing = array1[3]

print("Simple Indexing:",simple_indexing)   


fancy_indexing = array1[[1, 2, 5, 7]]

print("Fancy Indexing:",fancy_indexing)   

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]


Q2. Execute the 2D array Slicing.

In [1]:
import numpy as np

array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])

subarray1 = array1[:2, :2]
subarray2 = array1[1:3, 2:4]

print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


In [ ]:
Q3. Create the 5-Dimensional arrays using ndmin.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


Q4. Reshape the array from 1-D to 2-D array.

In [61]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)

print(arr_2d)


[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

a= np.stack((arr1, arr2), axis=0)
b = np.hstack((arr1, arr2))
c=np.vstack((arr1,arr2))
d=np.dstack((arr1,arr2))
print(a,"\n")
print(b,"\n")
print(c,"\n")
print(d,"\n")


[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[[1 4]
  [2 5]
  [3 6]]] 



Q6. Perform the searchsort method in Numpy array.

In [9]:
import numpy as np

arr = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 3 4 5]


Q7. Create Numpy Structured array using your domain features.

In [10]:
import numpy as np

dtype = [('name', 'U50'), ('price', float), ('availability', bool), ('category', 'U20')]

canteen_items = np.array([], dtype=dtype)

item1 = ('Sandwich', 5.99, True, 'Snacks')
item2 = ('Salad', 4.49, True, 'Healthy')
item3 = ('Pizza', 7.99, False, 'Fast Food')

canteen_items = np.array([item1, item2, item3], dtype=dtype)

print("Item Names:", canteen_items['name'])
print("Prices:", canteen_items['price'])
print("Availability:", canteen_items['availability'])
print("Categories:", canteen_items['category'])

snacks = canteen_items[canteen_items['category'] == 'Snacks']
print("\nSnacks:")
print(snacks)


Item Names: ['Sandwich' 'Salad' 'Pizza']
Prices: [5.99 4.49 7.99]
Availability: [ True  True False]
Categories: ['Snacks' 'Healthy' 'Fast Food']

Snacks:
[('Sandwich', 5.99,  True, 'Snacks')]


Q8. Create Data frame using List and Dictionary.

In [11]:
import pandas as pd

# Create a DataFrame using a list of dictionaries
data = [
    {'Name': 'Alice', 'Age': 28, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 32, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 24, 'City': 'Chicago'}
]

df_from_list_of_dicts = pd.DataFrame(data)

# Create a DataFrame using a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [28, 32, 24],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df_from_dict_of_lists = pd.DataFrame(data)

print("DataFrame created from a list of dictionaries:")
print(df_from_list_of_dicts)

print("\nDataFrame created from a dictionary of lists:")
print(df_from_dict_of_lists)


DataFrame created from a list of dictionaries:
      Name  Age         City
0    Alice   28     New York
1      Bob   32  Los Angeles
2  Charlie   24      Chicago

DataFrame created from a dictionary of lists:
      Name  Age         City
0    Alice   28     New York
1      Bob   32  Los Angeles
2  Charlie   24      Chicago


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.

In [30]:
import pandas as pd
df=pd.read_csv(r"university_canteen_data_with_nan.csv")
df=df.head(10)
df.isnull()

Student_ID  Student_Name  Student_Department  Student_Year  \
0       False         False               False         False   
1       False         False               False         False   
2       False          True               False         False   
3       False         False               False         False   
4       False         False               False         False   
5       False          True               False         False   
6       False         False               False         False   
7       False         False               False         False   
8       False         False               False         False   
9       False         False               False         False   

   Student_Contact_Info  Transaction_ID  Transaction_DateTime  Menu_Item_ID  \
0                 False           False                 False         False   
1                 False           False                 False         False   
2                 False           False                 False         False   
3                 False           False                 False         False   
4                 False           False                 False         False   
5                 False           False                 False         False   
6                 False           False                 False         False   
7                 False           False                 False         False   
8                 False           False                 False         False   
9                 False           False                 False         False   

   Quantity_Purchased  Total_Cost  ...  Rating  Comments  Staff_ID  \
0               False       False  ...   False      True     False   
1               False       False  ...   False     False     False   
2               False       False  ...   False     False     False   
3               False       False  ...   False     False     False   
4               False       False  ...   False     False     False   
5               False       False  ...   False     False     False   
6               False       False  ...   False      True     False   
7               False       False  ...   False     False     False   
8               False       False  ...   False      True     False   
9               False       False  ...   False     False     False   

   Staff_Name  Staff_Position  Staff_Contact_Info  Canteen_Location_ID  \
0       False           False               False                False   
1       False           False               False                False   
2       False           False               False                False   
3       False           False               False                False   
4       False           False               False                False   
5       False           False               False                False   
6       False           False               False                False   
7       False           False               False                False   
8       False           False               False                False   
9       False           False               False                False   

   Building_Name  Floor_Number  Seating_Capacity  
0          False         False             False  
1          False         False             False  
2          False         False             False  
3          False         False             False  
4          False         False             False  
5          False         False             False  
6          False         False             False  
7          False         False             False  
8          False         False             False  
9          False         False             False  

[10 rows x 30 columns]

In [29]:
df=df.head(7)
df.notnull()

Student_ID  Student_Name  Student_Department  Student_Year  \
0        True          True                True          True   
1        True          True                True          True   
2        True         False                True          True   
3        True          True                True          True   

   Student_Contact_Info  Transaction_ID  Transaction_DateTime  Menu_Item_ID  \
0                  True            True                  True          True   
1                  True            True                  True          True   
2                  True            True                  True          True   
3                  True            True                  True          True   

   Quantity_Purchased  Total_Cost  ...  Rating  Comments  Staff_ID  \
0                True        True  ...    True     False      True   
1                True        True  ...    True      True      True   
2                True        True  ...    True      True      True   
3                True        True  ...    True      True      True   

   Staff_Name  Staff_Position  Staff_Contact_Info  Canteen_Location_ID  \
0        True            True                True                 True   
1        True            True                True                 True   
2        True            True                True                 True   
3        True            True                True                 True   

   Building_Name  Floor_Number  Seating_Capacity  
0           True          True              True  
1           True          True              True  
2           True          True              True  
3           True          True              True  

[4 rows x 30 columns]

In [28]:
df=df.head(5)
df.dropna()

Student_ID    Student_Name Student_Department Student_Year  \
1        7890     Shelly Cruz              might    Sophomore   
3        5242  Kathleen Kelly              small       Junior   

  Student_Contact_Info  Transaction_ID Transaction_DateTime  Menu_Item_ID  \
1   vlewis@example.org           68373      4/11/2023 17:03            21   
3   qlopez@example.com           43977       2/1/2020 18:23            75   

   Quantity_Purchased  Total_Cost  ... Rating  \
1                   5        9.83  ...      5   
3                   3       11.08  ...      5   

                                            Comments Staff_ID      Staff_Name  \
1  Everybody this fill discussion end mother hers...      535    Emily Hansen   
3  Everything anything light somebody blue girl m...      843  Dr. Ian Castro   

   Staff_Position        Staff_Contact_Info  Canteen_Location_ID  \
1            Chef      dalton44@example.org                    2   
3          Waiter  ramirezholly@example.org                    3   

   Building_Name Floor_Number  Seating_Capacity  
1  Petersonmouth            1               112  
3     Dakotaside            2               144  

[2 rows x 30 columns]

In [27]:

df=df.head(5)
df.fillna("hello")


Student_ID    Student_Name Student_Department Student_Year  \
0        7311  Richard Barron                pay    Sophomore   
1        7890     Shelly Cruz              might    Sophomore   
2        1663           hello               type     Freshman   
3        5242  Kathleen Kelly              small       Junior   

   Student_Contact_Info  Transaction_ID Transaction_DateTime  Menu_Item_ID  \
0    qcrane@example.com           31715     10/10/2022 23:51            35   
1    vlewis@example.org           68373      4/11/2023 17:03            21   
2  cobbdana@example.com           18373       1/29/2020 7:08            20   
3    qlopez@example.com           43977       2/1/2020 18:23            75   

   Quantity_Purchased  Total_Cost  ... Rating  \
0                   2       13.57  ...      4   
1                   5        9.83  ...      5   
2                   5        3.06  ...      3   
3                   3       11.08  ...      5   

                                            Comments Staff_ID  \
0                                              hello      896   
1  Everybody this fill discussion end mother hers...      535   
2  About important operation laugh model. Particu...      657   
3  Everything anything light somebody blue girl m...      843   

         Staff_Name  Staff_Position           Staff_Contact_Info  \
0  Audrey Hernandez         Cashier  contrerasautumn@example.org   
1      Emily Hansen            Chef         dalton44@example.org   
2    Jamie Griffith            Chef      nicolebrown@example.com   
3    Dr. Ian Castro          Waiter     ramirezholly@example.org   

   Canteen_Location_ID  Building_Name Floor_Number  Seating_Capacity  
0                    2        Joeview            1                92  
1                    2  Petersonmouth            1               112  
2                    4       East Ian            3               187  
3                    3     Dakotaside            2               144  

[4 rows x 30 columns]

In [25]:
import pandas as pd

# Step 1: Read the CSV file into a DataFrame
df = pd.read_csv('university_canteen_data_with_nan.csv')

# Step 2: Perform the data replacement operation on the 'Quantity_Purchased' column
# For example, let's replace all occurrences of '10' with '20'
df['Quantity_Purchased'] = df['Quantity_Purchased'].replace(4, 5)

# Step 3: Write the modified DataFrame back to the same CSV file
df.to_csv('university_canteen_data_with_nan', index=False)
df=df.head(4)
df


Student_ID    Student_Name Student_Department Student_Year  \
0        7311  Richard Barron                pay    Sophomore   
1        7890     Shelly Cruz              might    Sophomore   
2        1663             NaN               type     Freshman   
3        5242  Kathleen Kelly              small       Junior   

   Student_Contact_Info  Transaction_ID Transaction_DateTime  Menu_Item_ID  \
0    qcrane@example.com           31715     10/10/2022 23:51            35   
1    vlewis@example.org           68373      4/11/2023 17:03            21   
2  cobbdana@example.com           18373       1/29/2020 7:08            20   
3    qlopez@example.com           43977       2/1/2020 18:23            75   

   Quantity_Purchased  Total_Cost  ... Rating  \
0                   2       13.57  ...      4   
1                   5        9.83  ...      5   
2                   5        3.06  ...      3   
3                   3       11.08  ...      5   

                                            Comments Staff_ID  \
0                                                NaN      896   
1  Everybody this fill discussion end mother hers...      535   
2  About important operation laugh model. Particu...      657   
3  Everything anything light somebody blue girl m...      843   

         Staff_Name  Staff_Position           Staff_Contact_Info  \
0  Audrey Hernandez         Cashier  contrerasautumn@example.org   
1      Emily Hansen            Chef         dalton44@example.org   
2    Jamie Griffith            Chef      nicolebrown@example.com   
3    Dr. Ian Castro          Waiter     ramirezholly@example.org   

   Canteen_Location_ID  Building_Name Floor_Number  Seating_Capacity  
0                    2        Joeview            1                92  
1                    2  Petersonmouth            1               112  
2                    4       East Ian            3               187  
3                    3     Dakotaside            2               144  

[4 rows x 30 columns]

In [60]:
import pandas as pd

# Step 1: Read the CSV file into a DataFrame
df = pd.read_csv('university_canteen_data_with_nan.csv')
b=df.interpolate(method='linear', inplace=True)
df.head(5)


# Step 3: Write the modified DataFrame back to the same CSV file



Student_ID    Student_Name Student_Department Student_Year  \
0        7311  Richard Barron                pay    Sophomore   
1        7890     Shelly Cruz              might    Sophomore   
2        1663             NaN               type     Freshman   
3        5242  Kathleen Kelly              small       Junior   
4        9376   Heather Brown            billion     Freshman   

     Student_Contact_Info  Transaction_ID Transaction_DateTime  Menu_Item_ID  \
0      qcrane@example.com           31715     10/10/2022 23:51            35   
1      vlewis@example.org           68373      4/11/2023 17:03            21   
2    cobbdana@example.com           18373       1/29/2020 7:08            20   
3      qlopez@example.com           43977       2/1/2020 18:23            75   
4  kimberly71@example.net           30668      7/22/2020 13:01            38   

   Quantity_Purchased  Total_Cost  ... Rating  \
0                   2       13.57  ...      4   
1                   4        9.83  ...      5   
2                   4        3.06  ...      3   
3                   3       11.08  ...      5   
4                   5       12.53  ...      4   

                                            Comments Staff_ID  \
0                                                NaN      896   
1  Everybody this fill discussion end mother hers...      535   
2  About important operation laugh model. Particu...      657   
3  Everything anything light somebody blue girl m...      843   
4  Within politics ahead guess note relationship....      667   

         Staff_Name  Staff_Position           Staff_Contact_Info  \
0  Audrey Hernandez         Cashier  contrerasautumn@example.org   
1      Emily Hansen            Chef         dalton44@example.org   
2    Jamie Griffith            Chef      nicolebrown@example.com   
3    Dr. Ian Castro          Waiter     ramirezholly@example.org   
4  Christopher King          Waiter  sanchezcourtney@example.net   

   Canteen_Location_ID  Building_Name Floor_Number  Seating_Capacity  
0                    2        Joeview            1                92  
1                    2  Petersonmouth            1               112  
2                    4       East Ian            3               187  
3                    3     Dakotaside            2               144  
4                    3       New Ryan            1               173  

[5 rows x 30 columns]

Q10. Perform the Hierarchical Indexing in the above created dataset.

In [52]:
import pandas as pd

# Read the CSV file without a hierarchical index
df = pd.read_csv('university_canteen_data_with_nan.csv')


df.set_index(['Menu_Item_ID', 'Total_Cost'], inplace=True)
a=df.head(5)
b=a.sort_index()
b


Student_ID    Student_Name Student_Department  \
Menu_Item_ID Total_Cost                                                  
20           3.06              1663             NaN               type   
21           9.83              7890     Shelly Cruz              might   
35           13.57             7311  Richard Barron                pay   
38           12.53             9376   Heather Brown            billion   
75           11.08             5242  Kathleen Kelly              small   

                        Student_Year    Student_Contact_Info  Transaction_ID  \
Menu_Item_ID Total_Cost                                                        
20           3.06           Freshman    cobbdana@example.com           18373   
21           9.83          Sophomore      vlewis@example.org           68373   
35           13.57         Sophomore      qcrane@example.com           31715   
38           12.53          Freshman  kimberly71@example.net           30668   
75           11.08            Junior      qlopez@example.com           43977   

                        Transaction_DateTime  Quantity_Purchased  \
Menu_Item_ID Total_Cost                                            
20           3.06             1/29/2020 7:08                   4   
21           9.83            4/11/2023 17:03                   4   
35           13.57          10/10/2022 23:51                   2   
38           12.53           7/22/2020 13:01                   5   
75           11.08            2/1/2020 18:23                   3   

                        Payment_Method Menu_Item_Name  ... Rating  \
Menu_Item_ID Total_Cost                                ...          
20           3.06                 Cash         debate  ...      3   
21           9.83                 Cash       discover  ...      5   
35           13.57                Card         amount  ...      4   
38           12.53                Card       decision  ...      4   
75           11.08                Cash       property  ...      5   

                                                                  Comments  \
Menu_Item_ID Total_Cost                                                      
20           3.06        About important operation laugh model. Particu...   
21           9.83        Everybody this fill discussion end mother hers...   
35           13.57                                                     NaN   
38           12.53       Within politics ahead guess note relationship....   
75           11.08       Everything anything light somebody blue girl m...   

                         Staff_ID        Staff_Name  Staff_Position  \
Menu_Item_ID Total_Cost                                               
20           3.06             657    Jamie Griffith            Chef   
21           9.83             535      Emily Hansen            Chef   
35           13.57            896  Audrey Hernandez         Cashier   
38           12.53            667  Christopher King          Waiter   
75           11.08            843    Dr. Ian Castro          Waiter   

                                  Staff_Contact_Info Canteen_Location_ID  \
Menu_Item_ID Total_Cost                                                    
20           3.06            nicolebrown@example.com                   4   
21           9.83               dalton44@example.org                   2   
35           13.57       contrerasautumn@example.org                   2   
38           12.53       sanchezcourtney@example.net                   3   
75           11.08          ramirezholly@example.org                   3   

                         Building_Name  Floor_Number Seating_Capacity  
Menu_Item_ID Total_Cost                                                
20           3.06             East Ian             3              187  
21           9.83        Petersonmouth             1              112  
35           13.57             Joeview             1               92  
38           12.53            New Ryan        