Q1. Create two 3×3 matrices using the random function in Numpy and perform the
following operations. è Product (prod) è Multiplication (multiply) è Dot Product (dot)

In [1]:
import numpy as np
x = np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)
c=np.multiply(x,y)
a=np.matmul(x,y)
b=np.dot(x,y)
print("product")
print(c)
print("multiply")
print(a)
print("dot product")
print(b)

[[6 5 5]
 [5 1 3]
 [9 7 3]]
[[1 2 7]
 [7 9 6]
 [7 1 4]]
product
[[ 6 10 35]
 [35  9 18]
 [63  7 12]]
multiply
[[ 76  62  92]
 [ 33  22  53]
 [ 79  84 117]]
dot product
[[ 76  62  92]
 [ 33  22  53]
 [ 79  84 117]]


Q2. Perform the following set operations using the Numpy functions. è Union è Intersection
è Set difference è XOR

In [2]:
a=np.array([1,3,5,7,3])
b=np.array([5,3,1,9,11])
print("union")
c=np.union1d(a,b)
print(c)
print("intersection")
d=np.intersect1d(a,b)
print(d)
print("set difference")
e=np.setdiff1d(a,b)
print(e)
print("xor")
f=np.bitwise_xor(a,b)
print(f)


union
[ 1  3  5  7  9 11]
intersection
[1 3 5]
set difference
[7]
xor
[ 4  0  4 14  8]


Q3. Create a 1D array using Random function and perform the following operations. è
Cumulative sum è Cumulative Product è Discrete difference (with n=3) è Find the unique
elements from the array


In [3]:
a=np.random.randint(1,10,(6))
print("given array")
print(a)
b=np.cumsum(a)
print("cummulative sum")
print(b)
print("cummulative product")
c=np.cumprod(a)
print(c)
print("discrete difference")
d=np.diff(a,n=3)
print(d)
e=np.unique(a)
print("unique")
print(e)

given array
[4 4 8 2 9 4]
cummulative sum
[ 4  8 16 18 27 31]
cummulative product
[   4   16  128  256 2304 9216]
discrete difference
[-14  23 -25]
unique
[2 4 8 9]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined
function (frompyfunc())


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined
function (frompyfunc())

In [5]:
a=np.random.randint(1,20,(5))
print("first array")
print(a)
b=np.random.randint(1,20,(5))
print("second array")
print(b)
c=np.array([a+b for a,b in zip(a,b)])
print("zip function")
print(c)
d=np.add(a,b)
print("add function")
print(d)
def add(set1, set2):
 for i in range(len(set1)):
    set1[i] += set2[i]
    return set1
add(a,b)



first array
[ 9 11 14 11  4]
second array
[15  9 14 17  1]
zip function
[24 20 28 28  5]
add function
[24 20 28 28  5]


array([24, 11, 14, 11,  4])

Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array
of elements using reduce().

In [8]:

from functools import reduce
import numpy as np
from math import gcd
input_str = input("Enter values for the array comma-separated: ")
a = np.array([int(x) for x in input_str.split(',')])
def calculate_lcm(x, y):
 return x * y // gcd(x, y)
def calculate_gcd(x, y):
 while y != 0:
     x, y = y, x % y
     return x
lcm = reduce(calculate_lcm, a)
gcd = reduce(calculate_gcd, a)
print("LCM:", lcm)
print("GCD:", gcd)


LCM: 15
GCD: 5
